# Generated by Django 5.2 on 2025-05-09 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('stream', models.CharField(choices=[('Science', 'Science'), ('Commerce', 'Commerce'), ('Humanities', 'Humanities')], max_length=20)),
                ('subject1_name', models.CharField(max_length=100)),
                ('subject1_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('subject2_name', models.CharField(max_length=100)),
                ('subject2_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('subject3_name', models.CharField(max_length=100)),
                ('subject3_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('subject4_name', models.CharField(max_length=100)),
                ('subject4_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('subject5_name', models.CharField(max_length=100)),
                ('subject5_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('intrest', models.TextField()),
                ('guidance', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('Password', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('Password', models.CharField(max_length=14)),
                ('specification', models.CharField(max_length=40)),
                ('qualfication', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
