# Generated by Django 5.2 on 2025-05-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_delete_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='Password',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='email',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='name',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='specification',
            field=models.CharField(max_length=100),
        ),
    ]
