# Generated by Django 5.2 on 2025-05-13 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_teacher_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='qualfication',
            new_name='qualification',
        ),
    ]
